name: build-cron

on:
  push:
    tags:
      - 'v*'

jobs:
  build-cron:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - uses: actions/checkout@v3
      - name: Install upx
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - run: |
          go get -u 
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -tags=windows -ldflags "-s -w -H=windowsgui" -o cron_bilitools_amd64.exe main.go cmd_windows.go
          CGO_ENABLED=0 GOOS=windows GOARCH=arm64 go build -tags=windows -ldflags "-s -w -H=windowsgui" -o cron_bilitools_arm64.exe main.go cmd_windows.go
          upx -9 cron_bilitools_amd64.exe
      - name: Zip
        run: |
          tar -czf cron_bilitools_amd64.tar.gz cron_bilitools_amd64.exe README.md
          tar -czf cron_bilitools_arm64.tar.gz cron_bilitools_arm64.exe README.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cron_bilitools_arm64.tar.gz
            cron_bilitools_amd64.tar.gz
          draft: false
          prerelease: false
